# Generated by Django 3.2.5 on 2021-09-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('execution_time', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_column='First name', max_length=200, verbose_name='First_name')),
                ('last_name', models.CharField(db_column='Last name', max_length=200, verbose_name='Last_name')),
                ('age', models.IntegerField(db_column='Age', verbose_name='Age')),
                ('phone_number', models.CharField(blank=True, db_column='Phone number', max_length=12, null=True, unique=True)),
                ('group_id', models.ForeignKey(db_column='Group ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
    ]
