# Generated by Django 3.2.5 on 2021-08-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('execution_time', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last_name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True)),
            ],
        ),
    ]
