# Generated by Django 3.2.5 on 2021-09-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(db_column='Age', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(db_column='First name', max_length=200, verbose_name='First_name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(db_column='Last name', max_length=200, verbose_name='Last_name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, db_column='Phone number', max_length=12, null=True, unique=True),
        ),
    ]
