# Generated by Django 3.2.5 on 2021-08-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210817_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='execution_time',
            field=models.TimeField(null=True),
        ),
    ]
