# Generated by Django 3.2.5 on 2021-09-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_id',
        ),
    ]
