# Generated by Django 3.2.5 on 2021-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_logger_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logger',
            name='execution_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
