# Generated by Django 3.2.5 on 2021-08-16 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_logger_execution_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
    ]
