# Generated by Django 3.2.5 on 2021-09-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_id',
            new_name='group_name',
        ),
    ]
