# Generated by Django 3.2.5 on 2021-09-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_rename_group_id_student_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='group_name',
            new_name='group_id',
        ),
    ]
