# Generated by Django 3.2.5 on 2021-09-11 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0008_alter_student_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group_id',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Куратор'),
        ),
    ]
