# Generated by Django 3.2.5 on 2021-09-11 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_group_monitor'),
        ('students', '0009_auto_20210911_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='in_group',
            field=models.ForeignKey(db_column='Group ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.group', verbose_name='Group ID'),
        ),
    ]
