# Generated by Django 3.2.5 on 2021-11-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
    ]
