language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - flake8 .
  - python manage.py validate_templates
  - python manage.py check
  - python manage.py makemigrations --check --dry-run
  - pip check