language: python
python:
  - "3.9"
  - "3.8"
  - "3.7"
install:
  - poetry install
env:
  -SECRET_KEY='TEST'
script:
  - poetry run flake8 .
  - poetry run python manage.py collectstatic
  - poetry run python manage.py validate_templates
  - poetry run python manage.py check
  - poetry run python manage.py makemigrations --check --dry-run
  - poetry run pip check
  - poetry run pytest -s

services:
  - postgresql

before_script:
  - pip install poetry
  - psql -c 'create database travis_ci_test;' -U postgres


