# Generated by Django 3.2.5 on 2021-09-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(choices=[], max_length=4)),
                ('source', models.CharField(max_length=20)),
                ('price_for_buy', models.DecimalField(decimal_places=6, max_digits=15)),
                ('price_for_sell', models.DecimalField(decimal_places=6, max_digits=15)),
            ],
        ),
    ]
