# Generated by Django 3.2.5 on 2021-09-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_column='Creation date'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[], db_column='Currency', max_length=4),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price_for_buy',
            field=models.DecimalField(db_column='Buy price', decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='currency',
            name='price_for_sell',
            field=models.DecimalField(db_column='Sell price', decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='currency',
            name='source',
            field=models.CharField(db_column='Source', max_length=20),
        ),
    ]
