# Generated by Django 3.2.5 on 2021-09-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210912_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('RUR', 'Ruble')], db_column='Currency', max_length=4),
        ),
    ]
