# Generated by Django 3.2.5 on 2021-10-14 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_auto_20210914_0022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Currencies'},
        ),
    ]
