# Generated by Django 3.2.5 on 2021-09-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(db_column='Group name', max_length=200, verbose_name='Group Name')),
                ('students_in_group', models.IntegerField(db_column='Students in group', null=True, verbose_name='Students in group')),
                ('group_curator', models.OneToOneField(db_column='Group curator ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
        ),
    ]
