# Generated by Django 3.2.5 on 2021-09-10 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('students', '0001_initial'),
        ('group', '0002_group_group_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_curator',
            field=models.OneToOneField(db_column='Group curator ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_monitor',
            field=models.OneToOneField(db_column='Group monitor ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
