# Generated by Django 3.2.5 on 2021-09-08 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20210908_0046'),
        ('students', '0002_auto_20210908_0046'),
        ('group', '0003_alter_group_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_curator',
            field=models.ForeignKey(db_column='Group curator', null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_monitor',
            field=models.ForeignKey(db_column='Group monitor', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='group',
            name='students_in_group',
            field=models.IntegerField(db_column='Students in group', verbose_name='Students in group'),
        ),
    ]
