# Generated by Django 3.2.5 on 2021-09-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(db_column='Subject', max_length=200, verbose_name='Subject')),
                ('first_name', models.CharField(db_column='First name', max_length=200, verbose_name='First name')),
                ('last_name', models.CharField(db_column='Last name', max_length=200, verbose_name='Last name')),
                ('age', models.IntegerField(db_column='Age', verbose_name='Age')),
            ],
        ),
    ]
