# Generated by Django 3.2.5 on 2021-09-08 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(db_column='Age', verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(db_column='First name', max_length=200, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(db_column='Last name', max_length=200, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(db_column='Subject', max_length=200, verbose_name='Subject'),
        ),
    ]
